defaults:
  - environment: Bioniceye # Bioniceye or CartPole-v1
  - algorithm: DQN # PPO or REINFORCE or AC or DQN

server:
  ip: "127.0.0.1"
  port: 8888
  address: "${server.ip}:${server.port}"

seed: 0

# \ in Windows and / on Mac
train: RL # SL or RL

reinforcement:
  directory:
    image_dir: data\sample_for_dev_test # data\sample_for_dev_test2
    label_path: data\211105_QAs_for_Set0_CNN_SVC_4classes_partial.csv # data\211105_QAs_for_Set0_CNN_SVC_4classes_partial.csv or data\211107_QAs_for_Set0_CNN_SVC_4classes_partial_64PIX.csv
    pred_dir: data\Human_Expert\211202
    data_path: data\210827_ANNA_Removing_uncontaminated_data.csv
    pretrain_dir: data\Middle_Resolution_137_unzipped_parcropped_128_removed_train

  data:
    stim_type: opt # elec
    top1: True
    class_num: 16

  training:
    gamma: 0.99
    render: False
    print_interval: 20
    pre_epoch_num: 7

supervised:
  directory:
    image_dir: data\Middle_Resolution_137_unzipped_parcropped_128_removed_train
    data_path: data\210827_ANNA_Removing_uncontaminated_data.csv

  data:
    class_num: 16

  training:
    epoch_num: 1000
    print_interval: 20
    learning_rate: 1e-4
    batch_size: 16
    train_num: 1000

output_dir: outputs
monitor_tm: True
save_info: True
  

