defaults:
  - environment: CartPole-v1
  - algorithm: DQN

server:
  ip: "127.0.0.1"
  port: 8888
  address: "${server.ip}:${server.port}"

seed: 0

# \ in Windows and / on Mac
directory:
  image_dir: data\sample_for_dev_test # data\sample_for_dev_test2
  label_path: data\211105_QAs_for_Set0_CNN_SVC_4classes_partial.csv
  pred_dir: data\Human_Expert\211202
  data_path: data\210827_ANNA_Removing_uncontaminated_data.csv
  output_dir: outputs

data:
  stim_type: opt # elec
  top1: True
  class_num: 16

reinforcement:
  gamma: 0.99
  learning_rate: 0.0005

training:
  render: False
  print_interval: 20

monitor_tm: True
save_info: True
  

